# Generated by Django 5.1.1 on 2024-11-01 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyhome', '0002_favouritesongsmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistSongsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotifyhome.playlistmodel')),
                ('song_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotifyhome.songsmodel')),
            ],
        ),
        migrations.AddField(
            model_name='playlistmodel',
            name='songs',
            field=models.ManyToManyField(related_name='playlists', through='spotifyhome.PlaylistSongsModel', to='spotifyhome.songsmodel'),
        ),
    ]
