# Generated by Django 5.1.1 on 2024-11-02 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyhome', '0003_playlistmodel_playlistsongsmodel_playlistmodel_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistmodel',
            name='songs',
        ),
    ]
